<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<?php
	// acquire shared info from other files
	include("shared.php"); 
?>

<?php print ("$HTML");?>

	<div class="row">
		<div class="large-8 columns">
			<h4>Rules Regarding the Plots</h4>
			<p>This page covers the rules and procedures that the renters of the plots will be excepted to follow.</p>
			<ul>
				<li>Management of the garden has shifted from Arlington Parks and Recreation Dept. to the Community Garden Council.  Any questions or issues should be addressed to the Council, gardenatuta@gmail.com.</li>
				<br><li>Membership in the Garden Council is self-elected.  If you want to take part in decision-making, come to the Council’s monthly meetings and participate in the discussion.  Meetings are normally held on the second Thursday of every month, 5:15 pm, in the Parks Dept. building, 717 W Main St.</li>
				<br><li>Rental fee has been reduced to $25 per plot per year, payable only after your application has been reviewed and your plot number has been assigned – see Plot Rental Application for instructions.</li>
				<br><li>Plot assignments will be made on a first-come, first-served basis.</li>
				<br><li>Plot transfers without prior notification to the Garden Council will not be honored.  We must have an application on file for every person working a plot every year.</li>
				<br><li>Vegetable donations to Mission Arlington or other food pantries are optional but highly encouraged.</li>
				<br><li>Gardeners will be able to plant any food crops of their choosing.  Fruit trees that may shade adjacent plots are not allowed.</li>
				<br><li>A reasonable number of nitrogen-fixing and companion plantings are permitted.</li>
				<br><li>Free compost and mulch material will continue to be available on demand.  Well-aged manure is okay, but no commercial inorganic fertilizer or herbicide application is allowed in the garden at any time.</li>
				<br><li>Tools, supplies, and repairs to garden structures and equipment are paid by the Council from money generated by plot rental fees.  Please be careful how you use the facilities; our funds are limited and this policy may change if abused.</li>
				<br><li>Clean and put away tools and hoses after use; lock shed when you leave; keep your plantings and other stuff within the confines of your plot; and don’t waste water.</li>
			</ul>

			<h4>Note</h4>
			<p>We are all volunteers with jobs and busy lives, so please be patient.  In case of emergency you may call John at 817-504-1465 or Angela at 817-980-4264.</p>

		</div>
	</div>

<? print ("$footer");?>
 </body>
</html>
